@extends('layouts.admin')

@section('content')
<div class="space-y-8">

    <!-- Top Header -->
    <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
            <h1 class="text-2xl sm:text-3xl font-black text-white tracking-tight flex items-center gap-3">
                <span>📈 Platform Financials & Revenue Analytics</span>
            </h1>
            <p class="text-xs sm:text-sm text-slate-400 mt-1">
                Real-time accounting of platform commission fees, client deposit surcharges, connects token sales, and gross marketplace volume.
            </p>
        </div>
        <div class="flex items-center gap-3">
            <a href="{{ route('admin.settings') }}" class="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl text-xs font-bold transition flex items-center gap-2 shadow-lg shadow-emerald-950/40">
                <span>⚙️ Adjust Fee Rates</span>
            </a>
        </div>
    </div>

    <!-- Hero KPI Revenue Cards -->
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6">
        
        <!-- Total Platform Net Revenue -->
        <div class="bg-gradient-to-br from-emerald-950/80 via-slate-900 to-slate-900 border border-emerald-500/40 rounded-3xl p-6 shadow-xl relative overflow-hidden space-y-2">
            <div class="flex items-center justify-between">
                <span class="text-xs font-bold text-emerald-400 uppercase tracking-wider">Total Platform Revenue</span>
                <span class="p-2 rounded-xl bg-emerald-500/10 text-emerald-400 text-base">👑</span>
            </div>
            <div class="text-3xl sm:text-4xl font-black text-white tracking-tight">
                ${{ number_format($totalPlatformRevenue, 2) }}
            </div>
            <p class="text-[11px] text-emerald-300/80 font-medium">
                Net profit earned across all monetization streams
            </p>
        </div>

        <!-- Contract Take-Rate Commission -->
        <div class="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-2">
            <div class="flex items-center justify-between">
                <span class="text-xs font-bold text-slate-400 uppercase tracking-wider">Milestone Take-Rate ({{ $platformFeePercent }}%)</span>
                <span class="p-2 rounded-xl bg-slate-800 text-slate-300 text-base">🥇</span>
            </div>
            <div class="text-3xl font-black text-white tracking-tight">
                ${{ number_format($contractTakeRateRevenue, 2) }}
            </div>
            <p class="text-[11px] text-slate-400">
                Direct commission on released client milestones
            </p>
        </div>

        <!-- Gross Marketplace Volume (GMV) -->
        <div class="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-2">
            <div class="flex items-center justify-between">
                <span class="text-xs font-bold text-slate-400 uppercase tracking-wider">Gross Volume (GMV)</span>
                <span class="p-2 rounded-xl bg-slate-800 text-slate-300 text-base">🌐</span>
            </div>
            <div class="text-3xl font-black text-white tracking-tight">
                ${{ number_format($grossMarketplaceVolume, 2) }}
            </div>
            <p class="text-[11px] text-slate-400">
                Total transacted capital across contracts & deposits
            </p>
        </div>

        <!-- Escrow Protection Vault -->
        <div class="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-2">
            <div class="flex items-center justify-between">
                <span class="text-xs font-bold text-slate-400 uppercase tracking-wider">Escrow Vault Locked</span>
                <span class="p-2 rounded-xl bg-teal-500/10 text-teal-400 text-base">🛡️</span>
            </div>
            <div class="text-3xl font-black text-teal-400 tracking-tight">
                ${{ number_format($totalEscrowLocked, 2) }}
            </div>
            <p class="text-[11px] text-slate-400">
                Funds currently held securely in active contracts
            </p>
        </div>

    </div>

    <!-- Monetization Streams Breakdown -->
    <div class="bg-slate-900 border border-slate-800 rounded-3xl p-6 sm:p-8 space-y-6 shadow-xl">
        <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-4 border-b border-slate-800">
            <div>
                <h2 class="text-lg font-bold text-white flex items-center gap-2">
                    <span>📊 Platform Fee Streams Breakdown</span>
                </h2>
                <p class="text-xs text-slate-400 mt-0.5">Distribution of revenue generated by fee category</p>
            </div>
            <span class="text-xs font-bold text-slate-400">Platform Commission: <strong class="text-emerald-400">{{ $platformFeePercent }}%</strong></span>
        </div>

        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            @foreach($feeStreams as $key => $stream)
                <div class="p-5 rounded-2xl bg-slate-950/60 border border-slate-800 space-y-3">
                    <div class="flex items-center justify-between">
                        <span class="text-base">{{ $stream['icon'] }}</span>
                        <span class="text-xs font-black text-slate-300">{{ $stream['pct'] }}%</span>
                    </div>
                    <div>
                        <span class="text-xs font-semibold text-slate-400 block">{{ $stream['label'] }}</span>
                        <span class="text-xl font-black text-white block mt-0.5">${{ number_format($stream['amount'], 2) }}</span>
                    </div>
                    <!-- Progress Bar -->
                    <div class="w-full h-1.5 bg-slate-800 rounded-full overflow-hidden">
                        <div class="h-full bg-{{ $stream['color'] }}-500 rounded-full" style="width: {{ max(4, $stream['pct']) }}%"></div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>

    <!-- Itemized Platform Fee Revenue Ledger (Audit Table) -->
    <div class="bg-slate-900 border border-slate-800 rounded-3xl p-6 sm:p-8 space-y-6 shadow-xl">
        <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-800">
            <div>
                <h2 class="text-lg font-bold text-white flex items-center gap-2">
                    <span>🧾 Platform Fee Revenue Ledger</span>
                </h2>
                <p class="text-xs text-slate-400 mt-0.5">Audit log of every fee collected, milestone deduction, and transaction fee credited</p>
            </div>

            <!-- Filter Badges -->
            <div class="flex flex-wrap items-center gap-2">
                <a href="{{ route('admin.revenue') }}" class="px-3 py-1.5 rounded-xl text-xs font-bold transition {{ !request('type') ? 'bg-emerald-600 text-white' : 'bg-slate-800 text-slate-400 hover:text-white' }}">
                    All Events
                </a>
                <a href="{{ route('admin.revenue', ['type' => 'platform_fee']) }}" class="px-3 py-1.5 rounded-xl text-xs font-bold transition {{ request('type') === 'platform_fee' ? 'bg-emerald-600 text-white' : 'bg-slate-800 text-slate-400 hover:text-white' }}">
                    Take-Rate Fees
                </a>
                <a href="{{ route('admin.revenue', ['type' => 'payout_fee']) }}" class="px-3 py-1.5 rounded-xl text-xs font-bold transition {{ request('type') === 'payout_fee' ? 'bg-emerald-600 text-white' : 'bg-slate-800 text-slate-400 hover:text-white' }}">
                    Withdrawal Fees
                </a>
            </div>
        </div>

        <!-- Table -->
        <div class="overflow-x-auto">
            <table class="w-full text-left text-xs">
                <thead>
                    <tr class="border-b border-slate-800 text-slate-400 uppercase font-semibold">
                        <th class="pb-3">Date & Time</th>
                        <th class="pb-3">Stream Type</th>
                        <th class="pb-3">User / Participant</th>
                        <th class="pb-3">Description & Reference</th>
                        <th class="pb-3">Gross Value</th>
                        <th class="pb-3 text-right">Admin Profit Credited</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-slate-800/60">
                    @forelse($ledger as $item)
                        <tr class="hover:bg-slate-800/40 transition">
                            <td class="py-3.5 text-slate-400 font-medium">
                                {{ $item->created_at->format('M d, Y h:i A') }}
                            </td>
                            <td class="py-3.5">
                                @if($item->type === 'platform_fee')
                                    <span class="inline-block px-2.5 py-1 rounded-lg text-[10px] font-bold uppercase bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                                        🥇 Take-Rate Commission
                                    </span>
                                @elseif($item->type === 'payout')
                                    <span class="inline-block px-2.5 py-1 rounded-lg text-[10px] font-bold uppercase bg-amber-500/10 text-amber-400 border border-amber-500/20">
                                        💸 Withdrawal Fee
                                    </span>
                                @elseif($item->type === 'connects_purchase')
                                    <span class="inline-block px-2.5 py-1 rounded-lg text-[10px] font-bold uppercase bg-purple-500/10 text-purple-400 border border-purple-500/20">
                                        🎟️ Connects Sale
                                    </span>
                                @else
                                    <span class="inline-block px-2.5 py-1 rounded-lg text-[10px] font-bold uppercase bg-slate-800 text-slate-300">
                                        {{ str_replace('_', ' ', $item->type) }}
                                    </span>
                                @endif
                            </td>
                            <td class="py-3.5 text-slate-300 font-bold">
                                {{ $item->user->name ?? 'System' }}
                                <span class="block text-[10px] text-slate-500 font-normal">{{ $item->user->email ?? '' }}</span>
                            </td>
                            <td class="py-3.5 text-slate-300 max-w-xs truncate">
                                {{ $item->description }}
                            </td>
                            <td class="py-3.5 text-slate-400 font-medium">
                                ${{ number_format($item->amount, 2) }}
                            </td>
                            <td class="py-3.5 text-right font-black text-emerald-400 text-sm">
                                +${{ number_format($item->type === 'platform_fee' ? $item->amount : ($item->fee > 0 ? $item->fee : $item->amount), 2) }}
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6" class="py-8 text-center text-slate-500">
                                No fee events recorded yet. Platform fees will populate automatically as milestones and payouts are released.
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

        @if($ledger->hasPages())
            <div class="pt-4 border-t border-slate-800">
                {{ $ledger->links() }}
            </div>
        @endif
    </div>

</div>
@endsection
