-- WorkForge MySQL Database Dump for InfinityFree / phpMyAdmin
SET FOREIGN_KEY_CHECKS=0;

-- Table: categories
INSERT INTO `categories` (`id`, `name`, `slug`, `icon`, `description`, `parent_id`, `sort_order`, `is_popular`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `categories` (`id`, `name`, `slug`, `icon`, `description`, `parent_id`, `sort_order`, `is_popular`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `categories` (`id`, `name`, `slug`, `icon`, `description`, `parent_id`, `sort_order`, `is_popular`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `categories` (`id`, `name`, `slug`, `icon`, `description`, `parent_id`, `sort_order`, `is_popular`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `categories` (`id`, `name`, `slug`, `icon`, `description`, `parent_id`, `sort_order`, `is_popular`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `categories` (`id`, `name`, `slug`, `icon`, `description`, `parent_id`, `sort_order`, `is_popular`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );

-- Table: skills
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `skills` (`id`, `name`, `slug`, `category_id`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );

-- Table: users
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `role`, `avatar`, `phone`, `status`, `country`, `city`, `timezone`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `role`, `avatar`, `phone`, `status`, `country`, `city`, `timezone`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `role`, `avatar`, `phone`, `status`, `country`, `city`, `timezone`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `role`, `avatar`, `phone`, `status`, `country`, `city`, `timezone`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `role`, `avatar`, `phone`, `status`, `country`, `city`, `timezone`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `role`, `avatar`, `phone`, `status`, `country`, `city`, `timezone`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `role`, `avatar`, `phone`, `status`, `country`, `city`, `timezone`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `role`, `avatar`, `phone`, `status`, `country`, `city`, `timezone`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `role`, `avatar`, `phone`, `status`, `country`, `city`, `timezone`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `role`, `avatar`, `phone`, `status`, `country`, `city`, `timezone`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `role`, `avatar`, `phone`, `status`, `country`, `city`, `timezone`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . );
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `role`, `avatar`, `phone`, `status`, `country`, `city`, `timezone`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );

-- Table: client_profiles
INSERT INTO `client_profiles` (`id`, `user_id`, `company_name`, `company_website`, `company_size`, `industry`, `tagline`, `about`, `payment_verified`, `total_spent`, `hires_count`, `active_contracts_count`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `client_profiles` (`id`, `user_id`, `company_name`, `company_website`, `company_size`, `industry`, `tagline`, `about`, `payment_verified`, `total_spent`, `hires_count`, `active_contracts_count`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `client_profiles` (`id`, `user_id`, `company_name`, `company_website`, `company_size`, `industry`, `tagline`, `about`, `payment_verified`, `total_spent`, `hires_count`, `active_contracts_count`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );

-- Table: freelancer_profiles
INSERT INTO `freelancer_profiles` (`id`, `user_id`, `title`, `bio`, `hourly_rate`, `experience_level`, `availability`, `english_level`, `job_success_score`, `total_earnings`, `completed_jobs_count`, `total_hours_worked`, `github_url`, `linkedin_url`, `portfolio_url`, `portfolio_items`, `certifications`, `education`, `is_top_rated`, `created_at`, `updated_at`, `employment_history`, `languages`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL, NULL,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL);
INSERT INTO `freelancer_profiles` (`id`, `user_id`, `title`, `bio`, `hourly_rate`, `experience_level`, `availability`, `english_level`, `job_success_score`, `total_earnings`, `completed_jobs_count`, `total_hours_worked`, `github_url`, `linkedin_url`, `portfolio_url`, `portfolio_items`, `certifications`, `education`, `is_top_rated`, `created_at`, `updated_at`, `employment_history`, `languages`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL, NULL,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL);
INSERT INTO `freelancer_profiles` (`id`, `user_id`, `title`, `bio`, `hourly_rate`, `experience_level`, `availability`, `english_level`, `job_success_score`, `total_earnings`, `completed_jobs_count`, `total_hours_worked`, `github_url`, `linkedin_url`, `portfolio_url`, `portfolio_items`, `certifications`, `education`, `is_top_rated`, `created_at`, `updated_at`, `employment_history`, `languages`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL, NULL,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL);
INSERT INTO `freelancer_profiles` (`id`, `user_id`, `title`, `bio`, `hourly_rate`, `experience_level`, `availability`, `english_level`, `job_success_score`, `total_earnings`, `completed_jobs_count`, `total_hours_worked`, `github_url`, `linkedin_url`, `portfolio_url`, `portfolio_items`, `certifications`, `education`, `is_top_rated`, `created_at`, `updated_at`, `employment_history`, `languages`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL, NULL,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL);
INSERT INTO `freelancer_profiles` (`id`, `user_id`, `title`, `bio`, `hourly_rate`, `experience_level`, `availability`, `english_level`, `job_success_score`, `total_earnings`, `completed_jobs_count`, `total_hours_worked`, `github_url`, `linkedin_url`, `portfolio_url`, `portfolio_items`, `certifications`, `education`, `is_top_rated`, `created_at`, `updated_at`, `employment_history`, `languages`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL, NULL,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL);
INSERT INTO `freelancer_profiles` (`id`, `user_id`, `title`, `bio`, `hourly_rate`, `experience_level`, `availability`, `english_level`, `job_success_score`, `total_earnings`, `completed_jobs_count`, `total_hours_worked`, `github_url`, `linkedin_url`, `portfolio_url`, `portfolio_items`, `certifications`, `education`, `is_top_rated`, `created_at`, `updated_at`, `employment_history`, `languages`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL, NULL,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL);
INSERT INTO `freelancer_profiles` (`id`, `user_id`, `title`, `bio`, `hourly_rate`, `experience_level`, `availability`, `english_level`, `job_success_score`, `total_earnings`, `completed_jobs_count`, `total_hours_worked`, `github_url`, `linkedin_url`, `portfolio_url`, `portfolio_items`, `certifications`, `education`, `is_top_rated`, `created_at`, `updated_at`, `employment_history`, `languages`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL, NULL, NULL, NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL);
INSERT INTO `freelancer_profiles` (`id`, `user_id`, `title`, `bio`, `hourly_rate`, `experience_level`, `availability`, `english_level`, `job_success_score`, `total_earnings`, `completed_jobs_count`, `total_hours_worked`, `github_url`, `linkedin_url`, `portfolio_url`, `portfolio_items`, `certifications`, `education`, `is_top_rated`, `created_at`, `updated_at`, `employment_history`, `languages`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL, NULL, NULL, NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL);

-- Table: user_skills
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `user_skills` (`id`, `user_id`, `skill_id`, `proficiency_level`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );

-- Table: job_postings
INSERT INTO `job_postings` (`id`, `client_id`, `category_id`, `title`, `slug`, `description`, `type`, `budget_min`, `budget_max`, `hourly_rate_min`, `hourly_rate_max`, `experience_level`, `duration`, `weekly_hours`, `status`, `proposals_count`, `hires_count`, `attachments`, `is_featured`, `is_urgent`, `published_at`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `job_postings` (`id`, `client_id`, `category_id`, `title`, `slug`, `description`, `type`, `budget_min`, `budget_max`, `hourly_rate_min`, `hourly_rate_max`, `experience_level`, `duration`, `weekly_hours`, `status`, `proposals_count`, `hires_count`, `attachments`, `is_featured`, `is_urgent`, `published_at`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `job_postings` (`id`, `client_id`, `category_id`, `title`, `slug`, `description`, `type`, `budget_min`, `budget_max`, `hourly_rate_min`, `hourly_rate_max`, `experience_level`, `duration`, `weekly_hours`, `status`, `proposals_count`, `hires_count`, `attachments`, `is_featured`, `is_urgent`, `published_at`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `job_postings` (`id`, `client_id`, `category_id`, `title`, `slug`, `description`, `type`, `budget_min`, `budget_max`, `hourly_rate_min`, `hourly_rate_max`, `experience_level`, `duration`, `weekly_hours`, `status`, `proposals_count`, `hires_count`, `attachments`, `is_featured`, `is_urgent`, `published_at`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `job_postings` (`id`, `client_id`, `category_id`, `title`, `slug`, `description`, `type`, `budget_min`, `budget_max`, `hourly_rate_min`, `hourly_rate_max`, `experience_level`, `duration`, `weekly_hours`, `status`, `proposals_count`, `hires_count`, `attachments`, `is_featured`, `is_urgent`, `published_at`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `job_postings` (`id`, `client_id`, `category_id`, `title`, `slug`, `description`, `type`, `budget_min`, `budget_max`, `hourly_rate_min`, `hourly_rate_max`, `experience_level`, `duration`, `weekly_hours`, `status`, `proposals_count`, `hires_count`, `attachments`, `is_featured`, `is_urgent`, `published_at`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );

-- Table: proposals
INSERT INTO `proposals` (`id`, `job_posting_id`, `freelancer_id`, `bid_amount`, `hourly_rate`, `platform_fee`, `receive_amount`, `delivery_time_days`, `cover_letter`, `milestones`, `attachments`, `status`, `client_seen`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `proposals` (`id`, `job_posting_id`, `freelancer_id`, `bid_amount`, `hourly_rate`, `platform_fee`, `receive_amount`, `delivery_time_days`, `cover_letter`, `milestones`, `attachments`, `status`, `client_seen`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );

-- Table: contracts
INSERT INTO `contracts` (`id`, `job_posting_id`, `proposal_id`, `client_id`, `freelancer_id`, `title`, `type`, `amount`, `platform_fee_percent`, `status`, `terms`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `contracts` (`id`, `job_posting_id`, `proposal_id`, `client_id`, `freelancer_id`, `title`, `type`, `amount`, `platform_fee_percent`, `status`, `terms`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `contracts` (`id`, `job_posting_id`, `proposal_id`, `client_id`, `freelancer_id`, `title`, `type`, `amount`, `platform_fee_percent`, `status`, `terms`, `start_date`, `end_date`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );

-- Table: contract_milestones
INSERT INTO `contract_milestones` (`id`, `contract_id`, `title`, `description`, `amount`, `due_date`, `status`, `submission_notes`, `submission_attachments`, `funded_at`, `submitted_at`, `released_at`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `contract_milestones` (`id`, `contract_id`, `title`, `description`, `amount`, `due_date`, `status`, `submission_notes`, `submission_attachments`, `funded_at`, `submitted_at`, `released_at`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL, NULL, NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `contract_milestones` (`id`, `contract_id`, `title`, `description`, `amount`, `due_date`, `status`, `submission_notes`, `submission_attachments`, `funded_at`, `submitted_at`, `released_at`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . , NULL,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `contract_milestones` (`id`, `contract_id`, `title`, `description`, `amount`, `due_date`, `status`, `submission_notes`, `submission_attachments`, `funded_at`, `submitted_at`, `released_at`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . , NULL,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . );

-- Table: wallets
INSERT INTO `wallets` (`id`, `user_id`, `balance`, `escrow_balance`, `currency`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `wallets` (`id`, `user_id`, `balance`, `escrow_balance`, `currency`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `wallets` (`id`, `user_id`, `balance`, `escrow_balance`, `currency`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `wallets` (`id`, `user_id`, `balance`, `escrow_balance`, `currency`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `wallets` (`id`, `user_id`, `balance`, `escrow_balance`, `currency`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `wallets` (`id`, `user_id`, `balance`, `escrow_balance`, `currency`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `wallets` (`id`, `user_id`, `balance`, `escrow_balance`, `currency`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `wallets` (`id`, `user_id`, `balance`, `escrow_balance`, `currency`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `wallets` (`id`, `user_id`, `balance`, `escrow_balance`, `currency`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `wallets` (`id`, `user_id`, `balance`, `escrow_balance`, `currency`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `wallets` (`id`, `user_id`, `balance`, `escrow_balance`, `currency`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `wallets` (`id`, `user_id`, `balance`, `escrow_balance`, `currency`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );

-- Table: transactions
INSERT INTO `transactions` (`id`, `wallet_id`, `user_id`, `type`, `amount`, `fee`, `reference_type`, `reference_id`, `description`, `status`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `transactions` (`id`, `wallet_id`, `user_id`, `type`, `amount`, `fee`, `reference_type`, `reference_id`, `description`, `status`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `transactions` (`id`, `wallet_id`, `user_id`, `type`, `amount`, `fee`, `reference_type`, `reference_id`, `description`, `status`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `transactions` (`id`, `wallet_id`, `user_id`, `type`, `amount`, `fee`, `reference_type`, `reference_id`, `description`, `status`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `transactions` (`id`, `wallet_id`, `user_id`, `type`, `amount`, `fee`, `reference_type`, `reference_id`, `description`, `status`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `transactions` (`id`, `wallet_id`, `user_id`, `type`, `amount`, `fee`, `reference_type`, `reference_id`, `description`, `status`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `transactions` (`id`, `wallet_id`, `user_id`, `type`, `amount`, `fee`, `reference_type`, `reference_id`, `description`, `status`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `transactions` (`id`, `wallet_id`, `user_id`, `type`, `amount`, `fee`, `reference_type`, `reference_id`, `description`, `status`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );

-- Table: reviews
INSERT INTO `reviews` (`id`, `contract_id`, `reviewer_id`, `reviewee_id`, `role`, `rating`, `communication_rating`, `quality_rating`, `deadline_rating`, `feedback`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `reviews` (`id`, `contract_id`, `reviewer_id`, `reviewee_id`, `role`, `rating`, `communication_rating`, `quality_rating`, `deadline_rating`, `feedback`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );

-- Table: disputes

-- Table: conversations
INSERT INTO `conversations` (`id`, `job_posting_id`, `contract_id`, `subject`, `last_message_at`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `conversations` (`id`, `job_posting_id`, `contract_id`, `subject`, `last_message_at`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `conversations` (`id`, `job_posting_id`, `contract_id`, `subject`, `last_message_at`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `conversations` (`id`, `job_posting_id`, `contract_id`, `subject`, `last_message_at`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . , NULL, NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );

-- Table: messages
INSERT INTO `messages` (`id`, `conversation_id`, `sender_id`, `body`, `attachments`, `is_read`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `messages` (`id`, `conversation_id`, `sender_id`, `body`, `attachments`, `is_read`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `messages` (`id`, `conversation_id`, `sender_id`, `body`, `attachments`, `is_read`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `messages` (`id`, `conversation_id`, `sender_id`, `body`, `attachments`, `is_read`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `messages` (`id`, `conversation_id`, `sender_id`, `body`, `attachments`, `is_read`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `messages` (`id`, `conversation_id`, `sender_id`, `body`, `attachments`, `is_read`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `messages` (`id`, `conversation_id`, `sender_id`, `body`, `attachments`, `is_read`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `messages` (`id`, `conversation_id`, `sender_id`, `body`, `attachments`, `is_read`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `messages` (`id`, `conversation_id`, `sender_id`, `body`, `attachments`, `is_read`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `messages` (`id`, `conversation_id`, `sender_id`, `body`, `attachments`, `is_read`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `messages` (`id`, `conversation_id`, `sender_id`, `body`, `attachments`, `is_read`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );
INSERT INTO `messages` (`id`, `conversation_id`, `sender_id`, `body`, `attachments`, `is_read`, `created_at`, `updated_at`) VALUES ( . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . , NULL,  . addslashes((string)) . ,  . addslashes((string)) . ,  . addslashes((string)) . );

-- Table: payout_requests

SET FOREIGN_KEY_CHECKS=1;
